/* download_github_keys.c generated by valac 0.26.1, the Vala compiler
 * generated from download_github_keys.vala, do not modify */

/* $ valac --pkg gio-2.0 --pkg gee-0.8 download_github_keys.vala*/
/* $ ./download_github_keys*/

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _CopyFileAsyncData CopyFileAsyncData;
typedef struct _DownloadGithubKeysData DownloadGithubKeysData;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))

struct _CopyFileAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	GFile* source;
	GFile* destination;
	GFile* _tmp0_;
	gboolean _tmp1_;
	GFile* _tmp2_;
	GFileInputStream* _tmp3_;
	GFile* _tmp4_;
	GFileInputStream* _tmp5_;
	GDataInputStream* dis;
	GDataInputStream* _tmp6_;
	GFileOutputStream* _tmp7_;
	GFile* _tmp8_;
	GFileOutputStream* _tmp9_;
	GDataOutputStream* dos;
	GDataOutputStream* _tmp10_;
	gchar* line;
	gchar* _tmp11_;
	GDataInputStream* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	const gchar* _tmp15_;
	GDataOutputStream* _tmp16_;
	const gchar* _tmp17_;
	GDataOutputStream* _tmp18_;
	GError* e;
	const gchar* _tmp19_;
	GError * _inner_error_;
};

struct _DownloadGithubKeysData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	gchar* username;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GFile* source_file;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	GFile* _tmp8_;
	GFile* _tmp9_;
	GFile* destination_file;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	GFile* _tmp14_;
	GFile* _tmp15_;
	const gchar* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
};


extern GMainLoop* main_loop;
GMainLoop* main_loop = NULL;

static void copy_file_async_data_free (gpointer _data);
void copy_file_async (GFile* source, GFile* destination, GAsyncReadyCallback _callback_, gpointer _user_data_);
void copy_file_finish (GAsyncResult* _res_);
static gboolean copy_file_async_co (CopyFileAsyncData* _data_);
static void copy_file_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void download_github_keys_data_free (gpointer _data);
void download_github_keys (const gchar* username, GAsyncReadyCallback _callback_, gpointer _user_data_);
void download_github_keys_finish (GAsyncResult* _res_);
static gboolean download_github_keys_co (DownloadGithubKeysData* _data_);
gint _vala_main (gchar** args, int args_length1);
static void ____lambda4_ (GObject* obj, GAsyncResult* res);
static void _____lambda4__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);


static void copy_file_async_data_free (gpointer _data) {
	CopyFileAsyncData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->source);
	_g_object_unref0 (_data_->destination);
	g_slice_free (CopyFileAsyncData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void copy_file_async (GFile* source, GFile* destination, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	CopyFileAsyncData* _data_;
	GFile* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	_data_ = g_slice_new0 (CopyFileAsyncData);
	_data_->_async_result = g_simple_async_result_new (NULL, _callback_, _user_data_, copy_file_async);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, copy_file_async_data_free);
	_tmp0_ = source;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data_->source);
	_data_->source = _tmp1_;
	_tmp2_ = destination;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (_data_->destination);
	_data_->destination = _tmp3_;
	copy_file_async_co (_data_);
}


void copy_file_finish (GAsyncResult* _res_) {
	CopyFileAsyncData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void copy_file_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	CopyFileAsyncData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	copy_file_async_co (_data_);
}


static gboolean copy_file_async_co (CopyFileAsyncData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	{
		_data_->_tmp0_ = NULL;
		_data_->_tmp0_ = _data_->destination;
		_data_->_tmp1_ = FALSE;
		_data_->_tmp1_ = g_file_query_exists (_data_->_tmp0_, NULL);
		if (_data_->_tmp1_) {
			_data_->_tmp2_ = NULL;
			_data_->_tmp2_ = _data_->destination;
			g_file_delete (_data_->_tmp2_, NULL, &_data_->_inner_error_);
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
				goto __catch0_g_error;
			}
		}
		_data_->_tmp4_ = NULL;
		_data_->_tmp4_ = _data_->source;
		_data_->_tmp5_ = NULL;
		_data_->_tmp5_ = g_file_read (_data_->_tmp4_, NULL, &_data_->_inner_error_);
		_data_->_tmp3_ = _data_->_tmp5_;
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
			goto __catch0_g_error;
		}
		_data_->_tmp6_ = NULL;
		_data_->_tmp6_ = g_data_input_stream_new ((GInputStream*) _data_->_tmp3_);
		_data_->dis = _data_->_tmp6_;
		_data_->_tmp8_ = NULL;
		_data_->_tmp8_ = _data_->destination;
		_data_->_tmp9_ = NULL;
		_data_->_tmp9_ = g_file_create (_data_->_tmp8_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_data_->_inner_error_);
		_data_->_tmp7_ = _data_->_tmp9_;
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
			_g_object_unref0 (_data_->dis);
			_g_object_unref0 (_data_->_tmp3_);
			goto __catch0_g_error;
		}
		_data_->_tmp10_ = NULL;
		_data_->_tmp10_ = g_data_output_stream_new ((GOutputStream*) _data_->_tmp7_);
		_data_->dos = _data_->_tmp10_;
		_data_->_state_ = 1;
		return FALSE;
		_state_1:
		;
		_data_->line = NULL;
		while (TRUE) {
			_data_->_tmp12_ = NULL;
			_data_->_tmp12_ = _data_->dis;
			_data_->_state_ = 2;
			g_data_input_stream_read_line_async (_data_->_tmp12_, G_PRIORITY_DEFAULT, NULL, copy_file_async_ready, _data_);
			return FALSE;
			_state_2:
			_data_->_tmp13_ = NULL;
			_data_->_tmp13_ = g_data_input_stream_read_line_finish (_data_->_tmp12_, _data_->_res_, NULL, &_data_->_inner_error_);
			_data_->_tmp11_ = _data_->_tmp13_;
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
				_g_free0 (_data_->line);
				_g_object_unref0 (_data_->dos);
				_g_object_unref0 (_data_->_tmp7_);
				_g_object_unref0 (_data_->dis);
				_g_object_unref0 (_data_->_tmp3_);
				goto __catch0_g_error;
			}
			_data_->_tmp14_ = NULL;
			_data_->_tmp14_ = _data_->_tmp11_;
			_data_->_tmp11_ = NULL;
			_g_free0 (_data_->line);
			_data_->line = _data_->_tmp14_;
			_data_->_tmp15_ = NULL;
			_data_->_tmp15_ = _data_->line;
			if (!(_data_->_tmp15_ != NULL)) {
				_g_free0 (_data_->_tmp11_);
				break;
			}
			_data_->_tmp16_ = NULL;
			_data_->_tmp16_ = _data_->dos;
			_data_->_tmp17_ = NULL;
			_data_->_tmp17_ = _data_->line;
			g_data_output_stream_put_string (_data_->_tmp16_, _data_->_tmp17_, NULL, &_data_->_inner_error_);
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
				_g_free0 (_data_->_tmp11_);
				_g_free0 (_data_->line);
				_g_object_unref0 (_data_->dos);
				_g_object_unref0 (_data_->_tmp7_);
				_g_object_unref0 (_data_->dis);
				_g_object_unref0 (_data_->_tmp3_);
				goto __catch0_g_error;
			}
			_data_->_tmp18_ = NULL;
			_data_->_tmp18_ = _data_->dos;
			g_data_output_stream_put_string (_data_->_tmp18_, "\n", NULL, &_data_->_inner_error_);
			if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
				_g_free0 (_data_->_tmp11_);
				_g_free0 (_data_->line);
				_g_object_unref0 (_data_->dos);
				_g_object_unref0 (_data_->_tmp7_);
				_g_object_unref0 (_data_->dis);
				_g_object_unref0 (_data_->_tmp3_);
				goto __catch0_g_error;
			}
			_g_free0 (_data_->_tmp11_);
		}
		_g_free0 (_data_->line);
		_g_object_unref0 (_data_->dos);
		_g_object_unref0 (_data_->_tmp7_);
		_g_object_unref0 (_data_->dis);
		_g_object_unref0 (_data_->_tmp3_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->e = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp19_ = NULL;
		_data_->_tmp19_ = _data_->e->message;
		g_error ("download_github_keys.vala:21: %s", _data_->_tmp19_);
		_g_error_free0 (_data_->e);
	}
	__finally0:
	if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void download_github_keys_data_free (gpointer _data) {
	DownloadGithubKeysData* _data_;
	_data_ = _data;
	_g_free0 (_data_->username);
	g_slice_free (DownloadGithubKeysData, _data_);
}


void download_github_keys (const gchar* username, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	DownloadGithubKeysData* _data_;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	_data_ = g_slice_new0 (DownloadGithubKeysData);
	_data_->_async_result = g_simple_async_result_new (NULL, _callback_, _user_data_, download_github_keys);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, download_github_keys_data_free);
	_tmp0_ = username;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (_data_->username);
	_data_->username = _tmp1_;
	download_github_keys_co (_data_);
}


void download_github_keys_finish (GAsyncResult* _res_) {
	DownloadGithubKeysData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gboolean download_github_keys_co (DownloadGithubKeysData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = NULL;
	_data_->_tmp0_ = _data_->username;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = string_to_string (_data_->_tmp0_);
	_data_->_tmp2_ = NULL;
	_data_->_tmp2_ = g_strconcat ("downloading keys for ", _data_->_tmp1_, "\n", NULL);
	_data_->_tmp3_ = NULL;
	_data_->_tmp3_ = _data_->_tmp2_;
	g_print ("%s", _data_->_tmp3_);
	_g_free0 (_data_->_tmp3_);
	_data_->_tmp4_ = NULL;
	_data_->_tmp4_ = _data_->username;
	_data_->_tmp5_ = NULL;
	_data_->_tmp5_ = string_to_string (_data_->_tmp4_);
	_data_->_tmp6_ = NULL;
	_data_->_tmp6_ = g_strconcat ("https://github.com/", _data_->_tmp5_, ".keys", NULL);
	_data_->_tmp7_ = NULL;
	_data_->_tmp7_ = _data_->_tmp6_;
	_data_->_tmp8_ = NULL;
	_data_->_tmp8_ = g_file_new_for_uri (_data_->_tmp7_);
	_data_->_tmp9_ = NULL;
	_data_->_tmp9_ = _data_->_tmp8_;
	_g_free0 (_data_->_tmp7_);
	_data_->source_file = _data_->_tmp9_;
	_data_->_tmp10_ = NULL;
	_data_->_tmp10_ = _data_->username;
	_data_->_tmp11_ = NULL;
	_data_->_tmp11_ = string_to_string (_data_->_tmp10_);
	_data_->_tmp12_ = NULL;
	_data_->_tmp12_ = g_strconcat (_data_->_tmp11_, ".keys", NULL);
	_data_->_tmp13_ = NULL;
	_data_->_tmp13_ = _data_->_tmp12_;
	_data_->_tmp14_ = NULL;
	_data_->_tmp14_ = g_file_new_for_path (_data_->_tmp13_);
	_data_->_tmp15_ = NULL;
	_data_->_tmp15_ = _data_->_tmp14_;
	_g_free0 (_data_->_tmp13_);
	_data_->destination_file = _data_->_tmp15_;
	copy_file_async (_data_->source_file, _data_->destination_file, NULL, NULL);
	_data_->_tmp16_ = NULL;
	_data_->_tmp16_ = _data_->username;
	_data_->_tmp17_ = NULL;
	_data_->_tmp17_ = string_to_string (_data_->_tmp16_);
	_data_->_tmp18_ = NULL;
	_data_->_tmp18_ = g_strconcat ("Downloaded keys for ", _data_->_tmp17_, "\n", NULL);
	_data_->_tmp19_ = NULL;
	_data_->_tmp19_ = _data_->_tmp18_;
	g_print ("%s", _data_->_tmp19_);
	_g_free0 (_data_->_tmp19_);
	_g_object_unref0 (_data_->destination_file);
	_g_object_unref0 (_data_->source_file);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void ____lambda4_ (GObject* obj, GAsyncResult* res) {
	GAsyncResult* _tmp0_ = NULL;
	GMainLoop* _tmp1_ = NULL;
	g_return_if_fail (res != NULL);
	_tmp0_ = res;
	download_github_keys_finish (_tmp0_);
	_tmp1_ = main_loop;
	g_main_loop_quit (_tmp1_);
}


static void _____lambda4__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
	____lambda4_ (source_object, res);
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GeeHashSet* usernames = NULL;
	GeeHashSet* _tmp0_ = NULL;
	GeeHashSet* _tmp1_ = NULL;
	GMainLoop* _tmp2_ = NULL;
	GMainLoop* _tmp10_ = NULL;
	_tmp0_ = gee_hash_set_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL);
	usernames = _tmp0_;
	_tmp1_ = usernames;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, "daniellawrence");
	_tmp2_ = g_main_loop_new (NULL, FALSE);
	_g_main_loop_unref0 (main_loop);
	main_loop = _tmp2_;
	{
		GeeIterator* _username_it = NULL;
		GeeHashSet* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		_tmp3_ = usernames;
		_tmp4_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) _tmp3_);
		_username_it = _tmp4_;
		while (TRUE) {
			GeeIterator* _tmp5_ = NULL;
			gboolean _tmp6_ = FALSE;
			gchar* username = NULL;
			GeeIterator* _tmp7_ = NULL;
			gpointer _tmp8_ = NULL;
			const gchar* _tmp9_ = NULL;
			_tmp5_ = _username_it;
			_tmp6_ = gee_iterator_next (_tmp5_);
			if (!_tmp6_) {
				break;
			}
			_tmp7_ = _username_it;
			_tmp8_ = gee_iterator_get (_tmp7_);
			username = (gchar*) _tmp8_;
			_tmp9_ = username;
			download_github_keys (_tmp9_, _____lambda4__gasync_ready_callback, NULL);
			_g_free0 (username);
		}
		_g_object_unref0 (_username_it);
	}
	_tmp10_ = main_loop;
	g_main_loop_run (_tmp10_);
	result = 0;
	_g_object_unref0 (usernames);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



