/* tree.c generated by valac 0.26.1, the Vala compiler
 * generated from tree.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>


#define TYPE_TREE_VIEW_SAMPLE (tree_view_sample_get_type ())
#define TREE_VIEW_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TREE_VIEW_SAMPLE, TreeViewSample))
#define TREE_VIEW_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TREE_VIEW_SAMPLE, TreeViewSampleClass))
#define IS_TREE_VIEW_SAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TREE_VIEW_SAMPLE))
#define IS_TREE_VIEW_SAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TREE_VIEW_SAMPLE))
#define TREE_VIEW_SAMPLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TREE_VIEW_SAMPLE, TreeViewSampleClass))

typedef struct _TreeViewSample TreeViewSample;
typedef struct _TreeViewSampleClass TreeViewSampleClass;
typedef struct _TreeViewSamplePrivate TreeViewSamplePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _TreeViewSample {
	GtkWindow parent_instance;
	TreeViewSamplePrivate * priv;
};

struct _TreeViewSampleClass {
	GtkWindowClass parent_class;
};


static gpointer tree_view_sample_parent_class = NULL;

GType tree_view_sample_get_type (void) G_GNUC_CONST;
enum  {
	TREE_VIEW_SAMPLE_DUMMY_PROPERTY
};
TreeViewSample* tree_view_sample_new (void);
TreeViewSample* tree_view_sample_construct (GType object_type);
static void tree_view_sample_setup_treeview (TreeViewSample* self, GtkTreeView* view);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
gint tree_view_sample_main (gchar** args, int args_length1);


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 13 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_main_quit ();
#line 55 "tree.c"
}


TreeViewSample* tree_view_sample_construct (GType object_type) {
	TreeViewSample * self = NULL;
	GtkTreeView* view = NULL;
	GtkTreeView* _tmp0_ = NULL;
#line 7 "/home/dannyla/code/github/learning_vala/tree.vala"
	self = (TreeViewSample*) g_object_new (object_type, NULL);
#line 8 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_window_set_title ((GtkWindow*) self, "TreeView Sample");
#line 9 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 250, 100);
#line 10 "/home/dannyla/code/github/learning_vala/tree.vala"
	_tmp0_ = (GtkTreeView*) gtk_tree_view_new ();
#line 10 "/home/dannyla/code/github/learning_vala/tree.vala"
	g_object_ref_sink (_tmp0_);
#line 10 "/home/dannyla/code/github/learning_vala/tree.vala"
	view = _tmp0_;
#line 11 "/home/dannyla/code/github/learning_vala/tree.vala"
	tree_view_sample_setup_treeview (self, view);
#line 12 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) view);
#line 13 "/home/dannyla/code/github/learning_vala/tree.vala"
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 7 "/home/dannyla/code/github/learning_vala/tree.vala"
	_g_object_unref0 (view);
#line 7 "/home/dannyla/code/github/learning_vala/tree.vala"
	return self;
#line 85 "tree.c"
}


TreeViewSample* tree_view_sample_new (void) {
#line 7 "/home/dannyla/code/github/learning_vala/tree.vala"
	return tree_view_sample_construct (TYPE_TREE_VIEW_SAMPLE);
#line 92 "tree.c"
}


static void tree_view_sample_setup_treeview (TreeViewSample* self, GtkTreeView* view) {
	GError * _inner_error_ = NULL;
#line 16 "/home/dannyla/code/github/learning_vala/tree.vala"
	g_return_if_fail (self != NULL);
#line 16 "/home/dannyla/code/github/learning_vala/tree.vala"
	g_return_if_fail (view != NULL);
#line 102 "tree.c"
	{
		GtkListStore* listmodel = NULL;
		GtkListStore* _tmp0_ = NULL;
		GtkTreeView* _tmp1_ = NULL;
		GtkListStore* _tmp2_ = NULL;
		GtkTreeView* _tmp3_ = NULL;
		GtkCellRendererText* _tmp4_ = NULL;
		GtkCellRendererText* _tmp5_ = NULL;
		GtkTreeView* _tmp6_ = NULL;
		GtkCellRendererText* _tmp7_ = NULL;
		GtkCellRendererText* _tmp8_ = NULL;
		GtkTreeIter iter = {0};
		gchar* home_dir = NULL;
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* download_dir = NULL;
		const gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		GFile* directory = NULL;
		const gchar* _tmp13_ = NULL;
		GFile* _tmp14_ = NULL;
		GFileEnumerator* enumerator = NULL;
		GFile* _tmp15_ = NULL;
		GFileEnumerator* _tmp16_ = NULL;
		gchar* file_name = NULL;
		gchar* _tmp17_ = NULL;
		GFileInfo* file_info = NULL;
#line 25 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp0_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING, -1);
#line 25 "/home/dannyla/code/github/learning_vala/tree.vala"
		listmodel = _tmp0_;
#line 26 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp1_ = view;
#line 26 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp2_ = listmodel;
#line 26 "/home/dannyla/code/github/learning_vala/tree.vala"
		gtk_tree_view_set_model (_tmp1_, (GtkTreeModel*) _tmp2_);
#line 28 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp3_ = view;
#line 28 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp4_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 28 "/home/dannyla/code/github/learning_vala/tree.vala"
		g_object_ref_sink (_tmp4_);
#line 28 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp5_ = _tmp4_;
#line 28 "/home/dannyla/code/github/learning_vala/tree.vala"
		gtk_tree_view_insert_column_with_attributes (_tmp3_, -1, "Image", (GtkCellRenderer*) _tmp5_, "text", 0, NULL);
#line 28 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_object_unref0 (_tmp5_);
#line 29 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp6_ = view;
#line 29 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp7_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 29 "/home/dannyla/code/github/learning_vala/tree.vala"
		g_object_ref_sink (_tmp7_);
#line 29 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp8_ = _tmp7_;
#line 29 "/home/dannyla/code/github/learning_vala/tree.vala"
		gtk_tree_view_insert_column_with_attributes (_tmp6_, -1, "Size", (GtkCellRenderer*) _tmp8_, "text", 1, NULL);
#line 29 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_object_unref0 (_tmp8_);
#line 33 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp9_ = g_get_home_dir ();
#line 33 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp10_ = g_strdup (_tmp9_);
#line 33 "/home/dannyla/code/github/learning_vala/tree.vala"
		home_dir = _tmp10_;
#line 34 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp11_ = home_dir;
#line 34 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp12_ = g_strconcat (_tmp11_, "/Downloads/", NULL);
#line 34 "/home/dannyla/code/github/learning_vala/tree.vala"
		download_dir = _tmp12_;
#line 36 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp13_ = download_dir;
#line 36 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp14_ = g_file_new_for_path (_tmp13_);
#line 36 "/home/dannyla/code/github/learning_vala/tree.vala"
		directory = _tmp14_;
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp15_ = directory;
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp16_ = g_file_enumerate_children (_tmp15_, "standard::*", 0, NULL, &_inner_error_);
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
		enumerator = _tmp16_;
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_object_unref0 (directory);
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_free0 (download_dir);
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_free0 (home_dir);
#line 37 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_object_unref0 (listmodel);
#line 198 "tree.c"
			goto __catch0_g_error;
		}
#line 38 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp17_ = g_strdup ("");
#line 38 "/home/dannyla/code/github/learning_vala/tree.vala"
		file_name = _tmp17_;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
		while (TRUE) {
#line 207 "tree.c"
			GFileInfo* _tmp18_ = NULL;
			GFileEnumerator* _tmp19_ = NULL;
			GFileInfo* _tmp20_ = NULL;
			GFileInfo* _tmp21_ = NULL;
			GFileInfo* _tmp22_ = NULL;
			GFileInfo* _tmp23_ = NULL;
			const gchar* _tmp24_ = NULL;
			gchar* _tmp25_ = NULL;
			gboolean file_name_ends_with_iso = FALSE;
			const gchar* _tmp26_ = NULL;
			gboolean _tmp27_ = FALSE;
			gboolean _tmp28_ = FALSE;
			FILE* _tmp29_ = NULL;
			gchar* file_size = NULL;
			GFileInfo* _tmp30_ = NULL;
			gint64 _tmp31_ = 0LL;
			gchar* _tmp32_ = NULL;
			GtkListStore* _tmp33_ = NULL;
			GtkTreeIter _tmp34_ = {0};
			GtkListStore* _tmp35_ = NULL;
			GtkTreeIter _tmp36_ = {0};
			const gchar* _tmp37_ = NULL;
			const gchar* _tmp38_ = NULL;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp19_ = enumerator;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp20_ = g_file_enumerator_next_file (_tmp19_, NULL, &_inner_error_);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp18_ = _tmp20_;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_object_unref0 (file_info);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_free0 (file_name);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_object_unref0 (enumerator);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_object_unref0 (directory);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_free0 (download_dir);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_free0 (home_dir);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_object_unref0 (listmodel);
#line 253 "tree.c"
				goto __catch0_g_error;
			}
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp21_ = _tmp18_;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp18_ = NULL;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_object_unref0 (file_info);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			file_info = _tmp21_;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp22_ = file_info;
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			if (!(_tmp22_ != NULL)) {
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_object_unref0 (_tmp18_);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
				break;
#line 272 "tree.c"
			}
#line 44 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp23_ = file_info;
#line 44 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp24_ = g_file_info_get_name (_tmp23_);
#line 44 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp25_ = g_strdup (_tmp24_);
#line 44 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_free0 (file_name);
#line 44 "/home/dannyla/code/github/learning_vala/tree.vala"
			file_name = _tmp25_;
#line 45 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp26_ = file_name;
#line 45 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp27_ = g_str_has_suffix (_tmp26_, ".iso");
#line 45 "/home/dannyla/code/github/learning_vala/tree.vala"
			file_name_ends_with_iso = _tmp27_;
#line 47 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp28_ = file_name_ends_with_iso;
#line 47 "/home/dannyla/code/github/learning_vala/tree.vala"
			if (_tmp28_ == FALSE) {
#line 48 "/home/dannyla/code/github/learning_vala/tree.vala"
				_g_object_unref0 (_tmp18_);
#line 48 "/home/dannyla/code/github/learning_vala/tree.vala"
				continue;
#line 298 "tree.c"
			}
#line 50 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp29_ = stderr;
#line 50 "/home/dannyla/code/github/learning_vala/tree.vala"
			fprintf (_tmp29_, "sleep");
#line 51 "/home/dannyla/code/github/learning_vala/tree.vala"
			g_usleep ((gulong) 1000000);
#line 53 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp30_ = file_info;
#line 53 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp31_ = g_file_info_get_size (_tmp30_);
#line 53 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp32_ = g_strdup_printf ("%" G_GINT64_FORMAT, _tmp31_);
#line 53 "/home/dannyla/code/github/learning_vala/tree.vala"
			file_size = _tmp32_;
#line 56 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp33_ = listmodel;
#line 56 "/home/dannyla/code/github/learning_vala/tree.vala"
			gtk_list_store_append (_tmp33_, &_tmp34_);
#line 56 "/home/dannyla/code/github/learning_vala/tree.vala"
			iter = _tmp34_;
#line 57 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp35_ = listmodel;
#line 57 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp36_ = iter;
#line 57 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp37_ = file_name;
#line 57 "/home/dannyla/code/github/learning_vala/tree.vala"
			_tmp38_ = file_size;
#line 57 "/home/dannyla/code/github/learning_vala/tree.vala"
			gtk_list_store_set (_tmp35_, &_tmp36_, 0, _tmp37_, 1, _tmp38_, -1);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_free0 (file_size);
#line 42 "/home/dannyla/code/github/learning_vala/tree.vala"
			_g_object_unref0 (_tmp18_);
#line 334 "tree.c"
		}
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_object_unref0 (file_info);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_free0 (file_name);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_object_unref0 (enumerator);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_object_unref0 (directory);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_free0 (download_dir);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_free0 (home_dir);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_object_unref0 (listmodel);
#line 350 "tree.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp39_ = NULL;
		GError* _tmp40_ = NULL;
		const gchar* _tmp41_ = NULL;
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		e = _inner_error_;
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_inner_error_ = NULL;
#line 62 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp39_ = stderr;
#line 62 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp40_ = e;
#line 62 "/home/dannyla/code/github/learning_vala/tree.vala"
		_tmp41_ = _tmp40_->message;
#line 62 "/home/dannyla/code/github/learning_vala/tree.vala"
		fprintf (_tmp39_, "Error: %s\n", _tmp41_);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		_g_error_free0 (e);
#line 373 "tree.c"
	}
	__finally0:
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		g_clear_error (&_inner_error_);
#line 23 "/home/dannyla/code/github/learning_vala/tree.vala"
		return;
#line 384 "tree.c"
	}
}


gint tree_view_sample_main (gchar** args, int args_length1) {
	gint result = 0;
	TreeViewSample* sample = NULL;
	TreeViewSample* _tmp0_ = NULL;
#line 68 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_init (&args_length1, &args);
#line 70 "/home/dannyla/code/github/learning_vala/tree.vala"
	_tmp0_ = tree_view_sample_new ();
#line 70 "/home/dannyla/code/github/learning_vala/tree.vala"
	g_object_ref_sink (_tmp0_);
#line 70 "/home/dannyla/code/github/learning_vala/tree.vala"
	sample = _tmp0_;
#line 71 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_widget_show_all ((GtkWidget*) sample);
#line 72 "/home/dannyla/code/github/learning_vala/tree.vala"
	gtk_main ();
#line 74 "/home/dannyla/code/github/learning_vala/tree.vala"
	result = 0;
#line 74 "/home/dannyla/code/github/learning_vala/tree.vala"
	_g_object_unref0 (sample);
#line 74 "/home/dannyla/code/github/learning_vala/tree.vala"
	return result;
#line 411 "tree.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 67 "/home/dannyla/code/github/learning_vala/tree.vala"
	return tree_view_sample_main (argv, argc);
#line 421 "tree.c"
}


static void tree_view_sample_class_init (TreeViewSampleClass * klass) {
#line 5 "/home/dannyla/code/github/learning_vala/tree.vala"
	tree_view_sample_parent_class = g_type_class_peek_parent (klass);
#line 428 "tree.c"
}


static void tree_view_sample_instance_init (TreeViewSample * self) {
}


GType tree_view_sample_get_type (void) {
	static volatile gsize tree_view_sample_type_id__volatile = 0;
	if (g_once_init_enter (&tree_view_sample_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TreeViewSampleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tree_view_sample_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TreeViewSample), 0, (GInstanceInitFunc) tree_view_sample_instance_init, NULL };
		GType tree_view_sample_type_id;
		tree_view_sample_type_id = g_type_register_static (gtk_window_get_type (), "TreeViewSample", &g_define_type_info, 0);
		g_once_init_leave (&tree_view_sample_type_id__volatile, tree_view_sample_type_id);
	}
	return tree_view_sample_type_id__volatile;
}



